<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NursingSurveySeeder extends Seeder
{
    public function run()
    {
        DB::table('nursing_survey_responses')->insert([
            [
                'survey_period' => '2025-06',
                'timestamp' => '2025-06-06 12:12:10',
                'dependencia' => 'Docente',
                'experiencia_enfermeria' => 'Excelente',
                'presentacion_personal' => 'Sí',
                'comentarios_presentacion' => '',
                'disponibilidad_personal' => 'Excelente',
                'comentarios_disponibilidad' => '',
                'profesionalismo' => 'Sí',
                'comentarios_profesionalismo' => '',
                'respuesta_efectiva' => 'Sí',
                'comentarios_respuesta' => '',
                'limpieza_orden' => 'Excelente',
                'comentarios_limpieza' => '',
                'reportes_oportunos' => 'Si',
                'comentarios_reportes' => '',
                'claridad_reportes' => 'Sí',
                'uploaded_by' => 1,
                'uploaded_at' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'survey_period' => '2025-06',
                'timestamp' => '2025-06-06 12:53:18',
                'dependencia' => 'Docente',
                'experiencia_enfermeria' => 'Excelente',
                'presentacion_personal' => 'Sí',
                'comentarios_presentacion' => '',
                'disponibilidad_personal' => 'Excelente',
                'comentarios_disponibilidad' => '',
                'profesionalismo' => 'Sí',
                'comentarios_profesionalismo' => '',
                'respuesta_efectiva' => 'Sí',
                'comentarios_respuesta' => '',
                'limpieza_orden' => 'Excelente',
                'comentarios_limpieza' => '',
                'reportes_oportunos' => 'Si',
                'comentarios_reportes' => '',
                'claridad_reportes' => 'Sí',
                'uploaded_by' => 1,
                'uploaded_at' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'survey_period' => '2025-06',
                'timestamp' => '2025-06-09 07:07:43',
                'dependencia' => 'Administrativo',
                'experiencia_enfermeria' => 'Excelente',
                'presentacion_personal' => 'Sí',
                'comentarios_presentacion' => '',
                'disponibilidad_personal' => 'Excelente',
                'comentarios_disponibilidad' => '',
                'profesionalismo' => 'Sí',
                'comentarios_profesionalismo' => '',
                'respuesta_efectiva' => 'Sí',
                'comentarios_respuesta' => '',
                'limpieza_orden' => 'Excelente',
                'comentarios_limpieza' => '',
                'reportes_oportunos' => 'Si',
                'comentarios_reportes' => '',
                'claridad_reportes' => 'Sí',
                'uploaded_by' => 1,
                'uploaded_at' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'survey_period' => '2025-06',
                'timestamp' => '2025-06-09 07:27:32',
                'dependencia' => 'Docente',
                'experiencia_enfermeria' => 'Buena',
                'presentacion_personal' => 'Sí',
                'comentarios_presentacion' => '',
                'disponibilidad_personal' => 'Buena',
                'comentarios_disponibilidad' => '',
                'profesionalismo' => 'Sí',
                'comentarios_profesionalismo' => '',
                'respuesta_efectiva' => 'No conozco este proceso',
                'comentarios_respuesta' => '',
                'limpieza_orden' => 'Excelente',
                'comentarios_limpieza' => '',
                'reportes_oportunos' => 'No conozco este proceso',
                'comentarios_reportes' => '',
                'claridad_reportes' => 'No conozco este proceso',
                'uploaded_by' => 1,
                'uploaded_at' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'survey_period' => '2025-06',
                'timestamp' => '2025-06-09 07:35:24',
                'dependencia' => 'Docente',
                'experiencia_enfermeria' => 'Buena',
                'presentacion_personal' => 'Sí',
                'comentarios_presentacion' => '',
                'disponibilidad_personal' => 'No conozco este proceso',
                'comentarios_disponibilidad' => '',
                'profesionalismo' => 'Sí',
                'comentarios_profesionalismo' => 'No he tenido que utilizar el servicio de enfermería hasta el momento, pero por lo que he observado, el personal actúa con profesionalismo y compromiso, siempre velando por el bienestar de los estudiantes.',
                'respuesta_efectiva' => 'No conozco este proceso',
                'comentarios_respuesta' => '',
                'limpieza_orden' => 'Bueno',
                'comentarios_limpieza' => '',
                'reportes_oportunos' => 'No conozco este proceso',
                'comentarios_reportes' => '',
                'claridad_reportes' => 'No conozco este proceso',
                'uploaded_by' => 1,
                'uploaded_at' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'survey_period' => '2025-06',
                'timestamp' => '2025-06-09 13:28:19',
                'dependencia' => 'Docente',
                'experiencia_enfermeria' => 'Excelente',
                'presentacion_personal' => 'Sí',
                'comentarios_presentacion' => '',
                'disponibilidad_personal' => 'Excelente',
                'comentarios_disponibilidad' => '',
                'profesionalismo' => 'Sí',
                'comentarios_profesionalismo' => '',
                'respuesta_efectiva' => 'Sí',
                'comentarios_respuesta' => '',
                'limpieza_orden' => 'Excelente',
                'comentarios_limpieza' => '',
                'reportes_oportunos' => 'Si',
                'comentarios_reportes' => 'La mayoría de veces esto sucede.',
                'claridad_reportes' => 'Sí',
                'uploaded_by' => 1,
                'uploaded_at' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'survey_period' => '2025-05',
                'timestamp' => '2025-05-15 10:30:00',
                'dependencia' => 'Administrativo',
                'experiencia_enfermeria' => 'Buena',
                'presentacion_personal' => 'Sí',
                'comentarios_presentacion' => '',
                'disponibilidad_personal' => 'Buena',
                'comentarios_disponibilidad' => '',
                'profesionalismo' => 'Sí',
                'comentarios_profesionalismo' => '',
                'respuesta_efectiva' => 'Sí',
                'comentarios_respuesta' => '',
                'limpieza_orden' => 'Bueno',
                'comentarios_limpieza' => '',
                'reportes_oportunos' => 'No conozco este proceso',
                'comentarios_reportes' => '',
                'claridad_reportes' => 'No conozco este proceso',
                'uploaded_by' => 1,
                'uploaded_at' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}
